### PR TITLE
fix: Generate valid VINs

### LINKED ISSUE #310: FFaker::Vehicle.vin should generate valid vins
Currently the ones it generates usually don't pass the [check digit test](https://en.wikibooks.org/wiki/Vehicle_Identification_Numbers_(VIN_codes)/Check_digit).

### PR DESCRIPTION
**Pull request by philippevezina**
The `TRANSLITERATION_VALUES` were not mapped because the Hash's keys are strings but `.to_sym` was called for the key mappings. Letters "O" and "Q" were also in VINs at times because `VALID_WMI_REGIONS` could randomly sample these letters.

Fixes #310

### CODE REVIEW

File: test/test_vehicle.rb [hunk 1]
```diff
@@ -5,6 +5,14 @@
 class TestVehicle < Test::Unit::TestCase
   include DeterministicHelper
 
+  # https://en.wikibooks.org/wiki/Vehicle_Identification_Numbers_(VIN_codes)/Check_digit
+  VIN_TRANSLITERATION_VALUES = {
```
Comment (masterT) [inline test/test_vehicle.rb:9]: Maybe support number as well, so there is a single mapping.

Comment (philippevezina) [reply test/test_vehicle.rb:9]: Yeah, I think we can keep this a simple bug fix for now :wink:

File: lib/ffaker/vehicle.rb [hunk 2]
```diff
@@ -53,7 +53,7 @@ def vin
 
         # Calculate the Check Digit
         weighted_sum = generated_vin.chars.each_with_index.sum do |char, idx|
-          (TRANSLITERATION_VALUES[char.to_sym] || char).to_i * POSITION_WEIGHTS[idx]
```
Comment (marocchino) [inline lib/ffaker/vehicle.rb:56]: 🤔
